FROM ubuntu:artful

ENV BUILD_HOME=/usr/local/prestopalette/

RUN mkdir -p $BUILD_HOME

# cd $BUILD_HOME
WORKDIR $BUILD_HOME

# cp * $BUILD_HOME
ADD . $BUILD_HOME

# ./docker_worker.sh
#RUN ./docker_worker.sh
